# Process a single image pair
name: image_correlation_pair
run-name: ${{ inputs.workflow_name }}

on:
  workflow_dispatch:
    inputs:
        img1_product_name:
            type: string
            required: true
            description: S2 image 1 product name
        img2_product_name:
            type: string
            required: true
            description: S2 image 2 product name 
        workflow_name:
            description: 'Custom workflow name'
            required: false
            default: 'autoRIFT'
            type: string

  workflow_call:
    inputs:
        img1_product_name:
            type: string
        img2_product_name:
            type: string
        workflow_name:
            type: string

jobs:
    autoRIFT:
        name: ${{ inputs.workflow_name }}
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -el {0}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install Conda environment with Micromamba
              uses: mamba-org/setup-micromamba@v1
              with:
                cache-environment: true
                # Pointing to the file inside your subfolder
                environment-file: glacier_image_correction/environment.yml

            - name: Modify autoRIFT Package
              # Fixed: Dynamically finding the folder to avoid the cp error
              run: |
                git clone https://github.com/gbrencher/autoRIFT.git
                AUTORIFT_DIR=$(python -c "import autoRIFT; print(autoRIFT.__path__[0])")
                echo "Found autoRIFT at: $AUTORIFT_DIR"
                cp -f autoRIFT/geo_autoRIFT/autoRIFT/autoRIFT.py "$AUTORIFT_DIR/"
                
            - name: Download Data and Run autoRIFT Software
              # Pointing to the script inside your subfolder
              run: |
                python glacier_image_correction/image_correlation.py ${{ inputs.img1_product_name }} ${{ inputs.img2_product_name }}

            - name: Upload Velocity Map as Artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{ inputs.workflow_name }}
                path: |
                    S2*horizontal_velocity.tif
